### ISSUE TITLE
__filename is not defined (ESM)

### ISSUE THREAD

**Issue by iDVB** [contentful/node-apps-toolkit#703]
Package doesn't support ESM?

`ReferenceError: __filename is not defined`
```
node_modules/.pnpm/@contentful+node-apps-toolkit@2.8.2/node_modules/@contentful/node-apps-toolkit/lib/keys/get-management-token.js102:179
        defaultCache = new NodeCache();
    }
    const httpClientOpts = typeof opts.host !== 'undefined' ? { prefixUrl: opts.host } : {};
    return (0, exports.createGetManagementToken)((0, utils_1.createLogger)({ filename: __filename }), (0, utils_1.createHttpClient)(httpClientOpts), defaultCache)(privateKey, opts);
};
exports.getManagementToken = getManagementToken;
```

Should likely has an ESM supported build?
```
// Import the URL module to resolve file paths
import { fileURLToPath } from 'url'

// ESM replacement for __filename
const __filename = fileURLToPath(import.meta.url)
```

**Comment by whitelisab** [comment]
Hi @iDVB! Thanks for this feedback, I've created a ticket in our team's backlog and we will keep you updated on it's progress.

**Comment by skotrola** [comment]
@whitelisab  Just an fyi, I seem to be getting a similar error that _could_ be related: 

```
{
    "errorType": "TypeError",
    "errorMessage": "The \"path\" argument must be of type string or an instance of URL. Received undefined",
    "code": "ERR_INVALID_ARG_TYPE",
    "stack": [
        "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string or an instance of URL. Received undefined",
        "    at fileURLToPath (node:internal/url:1487:11)",
        "    at getFilename (/var/task/index.js:27360:54)",
        "    at getDirname (/var/task/index.js:27361:52)",
        "    at Object.<anonymous> (/var/task/index.js:27362:33)",
        "    at Module._compile (node:internal/modules/cjs/loader:1469:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1288:32)",
        "    at Module._load (node:internal/modules/cjs/loader:1104:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1311:19)",
        "    at require (node:internal/modules/helpers:179:18)"
    ]
}
```
Tracing through this in my build file leads me to `var getFilename = () => (0, import_url.fileURLToPath)(import_meta.url);`. 
Import meta is defined as: `var import_meta = {};` and seems to never be updated.

I was using `@contentful/node-apps-toolkit": "3.10.2"`. 
Switching to `"@contentful/node-apps-toolkit": "3.9.2"` seemed to resolve the issue for me

**Comment by mscpdg** [comment]
i can see the same error as @skotrola in our lambdas, downgrading helped aswell.

**Comment by whitelisab** [comment]
Thanks for reporting these issues. I've notified the appropriate team so that they can look into this further.
